# Generated by Django 5.2.5 on 2025-09-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_email_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=99)),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='thread_id',
            field=models.IntegerField(default=-1),
        ),
    ]
